NineNineCats_auth/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root to: redirect('/cats')
end

NineNineCats_auth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <div class="ui container">

    <header class="ui header headerz">
      <div>
        <h1>
          <a href="<%= cats_url %>">99 Cats</a>
        </h1>
      </div>

      <div>
        <% if logged_in_user? %>
          <form action="<%= session_url %>" method="POST" class="ui form">
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" value="Logout" class="ui button basic red">
          </form>
        <% else %>
        <div class="header_nav">
          <a href="<%= new_user_url %>" class="ui button basic blue">Sign Up</a>
          <br><br>
          <a href="<%= new_session_url %>" class="ui button basic blue">Sign In</a>
        </div>
        <% end %>


      </div>
    </header>
        <% if current_user %>
          <p>Hello, <%= current_user.username %>!</p>
        <% else %>
          <p>Not currently logged in</p>
        <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>